import { type NextRequest, NextResponse } from "next/server"
import { generateText } from "ai"
import { createGoogleGenerativeAI } from "@ai-sdk/google"

const google = createGoogleGenerativeAI({
  apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
})

const DISCLAIMER = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AUTOMATED ANALYSIS DISCLAIMER

This analysis was generated by an AI-powered hospital billing verification 
system for informational purposes only. 

• This system serves as a neutral auditor for both patients and hospitals
• All calculations should be manually verified by qualified billing staff
• Discrepancies may have legitimate explanations (discounts, adjustments)
• Both parties should work collaboratively to resolve any differences

The system does not provide legal, medical, or financial advice.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`

export async function POST(request: NextRequest) {
  let requestData: any = null
  
  try {
    requestData = await request.json()
    const { 
      items, 
      totalOvercharge, 
      templateType = "verification",
      discrepancyDirection = "overcharge",
      calculatedTotal,
      statedTotal,
      difference
    } = requestData

    if (!items || items.length === 0) {
      throw new Error("No items provided")
    }

    const itemsList = items
      .map((item: any) => `- ${item.name}: ₱${item.total.toLocaleString()} (${item.reason})`)
      .join("\n")

    let prompt = ""

    if (templateType === "courtesy") {
      // Courtesy Notice for undercharges
      prompt = `Write a professional, helpful email to a hospital billing department reporting a potential underbilling discrepancy.

DISCREPANCY DETAILS:
• Sum of Itemized Charges: ₱${calculatedTotal?.toLocaleString()}
• Bill's Stated Subtotal: ₱${statedTotal?.toLocaleString()}
• Difference: ₱${difference?.toLocaleString()}

IDENTIFIED ITEMS:
${itemsList}

Email requirements:
- Subject line: "Billing Discrepancy Notice - Courtesy Report"
- Tone: Helpful, collaborative, neutral
- Explain the patient noticed they were charged LESS than the sum of itemized services
- This could indicate an applied discount not documented, calculation error, or billing adjustment
- Request verification and explanation of the difference
- Request documentation of any applied discounts/adjustments
- Frame as bringing this to their attention to ensure accurate billing for both parties
- Professional, respectful closing
- Use phrases like "may require attention", "could indicate", "please verify"
- NEVER use accusatory language

Format as complete email ready to send. Do not include markdown or code blocks.`
    } else if (templateType === "verification") {
      // Verification Request for overcharges
      prompt = `Write a professional, firm email to a hospital billing department requesting verification of charges due to a discrepancy.

DISCREPANCY DETAILS:
• Bill's Stated Subtotal: ₱${statedTotal?.toLocaleString()}
• Sum of Itemized Charges: ₱${calculatedTotal?.toLocaleString()}
• Difference: ₱${difference?.toLocaleString()}

IDENTIFIED ITEMS:
${itemsList}

Email requirements:
- Subject line: "Hospital Bill Discrepancy - Verification Requested"
- Tone: Professional, firm, fact-based
- Explain the billed subtotal exceeds the sum of individual line items
- This could indicate a calculation error, additional charges not itemized, or unapplied credit
- Request itemized verification of all charges
- Request explanation of the difference
- Request corrected statement if error is confirmed
- Request documentation of any additional charges not listed
- Professional, respectful closing
- Use phrases like "discrepancy detected", "request verification", "please provide"
- NEVER use accusatory language like "overcharged me" or "your math is wrong"

Format as complete email ready to send. Do not include markdown or code blocks.`
    } else {
      // Neutral Clarification Request
      prompt = `Write a neutral, polite email to a hospital billing department requesting clarification about a billing discrepancy.

DISCREPANCY DETAILS:
• Bill's Stated Subtotal: ₱${statedTotal?.toLocaleString()}
• Calculated Total from Line Items: ₱${calculatedTotal?.toLocaleString()}
• Difference: ₱${difference?.toLocaleString()}

IDENTIFIED ITEMS:
${itemsList}

Email requirements:
- Subject line: "Request for Clarification - Hospital Bill"
- Tone: Neutral, polite inquiry
- Mention noticing a difference between stated subtotal and calculated line items
- Ask questions: Can you verify the subtotal calculation? Are there applied discounts/adjustments not shown? Is additional documentation available?
- Express desire to understand the difference to ensure accuracy
- Professional, respectful closing
- Use phrases like "request clarification", "would appreciate assistance", "seeking understanding"
- Frame as collaborative resolution

Format as complete email ready to send. Do not include markdown or code blocks.`
    }

    const { text } = await generateText({
      model: google("gemini-2.0-flash-exp"),
      prompt,
    })

    // Add disclaimer to generated email
    const emailWithDisclaimer = text + "\n\n" + DISCLAIMER

    return NextResponse.json({ email: emailWithDisclaimer })
  } catch (error) {
    console.error("Error generating email:", error)

    // Use cached request data if available
    if (requestData) {
      const { 
        items = [], 
        totalOvercharge = 0, 
        templateType = "clarification",
        calculatedTotal = 0,
        statedTotal = 0,
        difference = 0
      } = requestData
      
      let fallbackEmail = ""
      
      if (templateType === "courtesy") {
        fallbackEmail = `Subject: Billing Discrepancy Notice - Courtesy Report

Dear Billing Department,

I am writing to report a mathematical discrepancy in my hospital bill that may require your attention.

DISCREPANCY DETAILS:
• Sum of Itemized Charges: ₱${calculatedTotal.toLocaleString()}
• Bill's Stated Subtotal: ₱${statedTotal.toLocaleString()}
• Difference: ₱${difference.toLocaleString()}

ANALYSIS:
The sum of individual line items exceeds the billed subtotal by ₱${difference.toLocaleString()}. This could indicate:

1. An applied discount not documented on the statement
2. A calculation error in the subtotal
3. A billing adjustment requiring clarification

IDENTIFIED ITEMS:
${items.map((item: any) => `- ${item.name}: ₱${item.total.toLocaleString()} - ${item.reason}`).join("\n")}

REQUESTED ACTION:
Please verify the calculation and provide:
• Explanation of the ₱${difference.toLocaleString()} difference
• Documentation of any applied discounts/adjustments
• Corrected statement if underbilling is confirmed

I am bringing this to your attention to ensure accurate billing for both parties.

Respectfully,
[Your Name]`
      } else if (templateType === "verification") {
        fallbackEmail = `Subject: Hospital Bill Discrepancy - Verification Requested

Dear Billing Department,

I am writing to request verification of charges on my recent hospital bill due to a mathematical discrepancy.

DISCREPANCY DETAILS:
• Bill's Stated Subtotal: ₱${statedTotal.toLocaleString()}
• Sum of Itemized Charges: ₱${calculatedTotal.toLocaleString()}
• Difference: ₱${difference.toLocaleString()}

ANALYSIS:
The billed subtotal exceeds the sum of individual line items by ₱${difference.toLocaleString()}. This could indicate:

1. A calculation error in the subtotal
2. Additional charges not itemized on the statement
3. An unapplied credit or payment

IDENTIFIED ITEMS:
${items.map((item: any) => `- ${item.name}: ₱${item.total.toLocaleString()} - ${item.reason}`).join("\n")}

REQUESTED ACTION:
Please provide:
• Itemized verification of all charges
• Explanation of the ₱${difference.toLocaleString()} difference
• Corrected statement if error is confirmed
• Documentation of any additional charges not listed

I appreciate your prompt attention to resolve this discrepancy accurately.

Respectfully,
[Your Name]`
      } else {
        fallbackEmail = `Subject: Request for Clarification - Hospital Bill

Dear Billing Department,

I am writing to request clarification regarding my recent hospital bill.

OBSERVATION:
Upon review, I noticed a ₱${difference.toLocaleString()} difference between:
• The stated subtotal: ₱${statedTotal.toLocaleString()}
• My calculation of line items: ₱${calculatedTotal.toLocaleString()}

IDENTIFIED ITEMS:
${items.map((item: any) => `- ${item.name}: ₱${item.total.toLocaleString()} - ${item.reason}`).join("\n")}

QUESTIONS:
1. Can you verify the subtotal calculation?
2. Are there any applied discounts or adjustments not shown?
3. Is there additional documentation available?

I would appreciate your assistance in understanding this difference to ensure the bill is accurate.

Thank you for your time.

Respectfully,
[Your Name]`
      }

      return NextResponse.json({ email: fallbackEmail + "\n\n" + DISCLAIMER })
    }
    
    return NextResponse.json(
      { error: "Failed to generate email" },
      { status: 500 }
    )
  }
}
